VAR A; 
CONST B = 19; 

FUNCTION FIBANACCI(VAL X); 
BEGIN
    IF X = 0 THEN
        FIBANACCI := 0;
    IF X = 1 THEN 
        FIBANACCI := 1; 
    IF X > 1 THEN 
        FIBANACCI := CALL FIBANACCI(X-2) + CALL FIBANACCI(X-1); 
END; 

BEGIN 
FOR A := 0 TO B-1 DO
    WRITE(CALL FIBANACCI(A));
WRITELN(CALL FIBANACCI(A)); 
END.  